# Generated by Django 5.1 on 2024-08-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link',
            new_name='silka',
        ),
    ]
