# Generated by Django 5.1 on 2024-08-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themain', '0002_rename_link_link_silka'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='urgency',
            new_name='number bruh',
        ),
    ]
