# Generated by Django 5.1 on 2024-08-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themain', '0003_rename_urgency_link_number_bruh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='number bruh',
        ),
        migrations.RemoveField(
            model_name='link',
            name='silka',
        ),
        migrations.AddField(
            model_name='link',
            name='lind',
            field=models.TextField(default=0, verbose_name='silka'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='urgency',
            field=models.IntegerField(default=0, verbose_name='number bruh'),
            preserve_default=False,
        ),
    ]
