# Generated by Django 5.1 on 2024-08-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themain', '0004_remove_link_number_bruh_remove_link_silka_link_lind_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='lind',
            new_name='link',
        ),
    ]
