# Generated by Django 5.1 on 2024-09-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themain', '0005_rename_lind_link_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='urgency',
            field=models.IntegerField(verbose_name='number_bruh'),
        ),
    ]
